### ISSUE TITLE
腾讯云API错误

### ISSUE THREAD

**Issue by GeorgeLZH0913** [liscs/MisakaTranslator#1]
腾讯云API错误 版本为v1.2.5

测试认证时显示请求头缺少参数

![Snipaste_2024-04-04_17-15-50](https://github.com/liscs/MisakaTranslator/assets/38287071/7530f91d-1bcc-4e83-b4b2-e3a69e47bb86)

**Comment by liscs** [comment]
v1.2.6修改了腾讯云的实现，可以再尝试下能否工作
